* !!PATHS used in this file!!
** See Magit "GIT_SSH"
* Things to do outside of emacs
  Search contents for "outside of emacs"

How to notes
* Emacs daemon server
  Run command: C:\Users\chany\Documents\Programming\emacs\emacs-26.3-x86_64\bin\emacsclientw.exe -c -n -a "" -f C:\Users\chany\Documents\Programming\emacs\.emacs.d\server\server
* Emacs Windows shortcut
  Create a windows shortcut file and give it a path: C:\Users\chany\Documents\Programming\emacs\emacs-26.3-x86_64\bin\emacsclientw.exe -c -n -a ""
* Basics
** C-x z: Repeats previous command. Run in once and then subsequently press z to repeat. e.g. C-p C-x z then zzzzzz
** M-%: find & replace string. Type 'y' to replace, '!' to replace all occurences below the point.

* In the minibuffer

** M-p moves to the previous input in minibuffer history.
** M-n moves to the next input in minibuffer
** M-r searches for an input that matches the supplied regexp.

* Register
** C-x r w REG 	Command: window-configuration-to-register
   Save the window configuration of current frame into register REG
** C-x r f REG 	Command: frame-configuration-to-register
   Save the state of all frames, including all their windows, in register REG
** C-x r j REG 	Command: jump-to-register
   Jump to a register REG.
* Macros
** F3 to begin recording Macro. If recording Macro and F3 is pressed again, it will insert an incrementor startig from zero. To set a starting point, before running a macro, press M-[number] F3. This will start recording a Macro and when F3 is pressed, incrementor with that number as the initial number will begin.
** F4 to end recording Macro. If ended and pressed F4 again, it will run Macro
** C-x C-k r: run the last keyboard macro on each line that begins in the region (apply-macro-to-region-lines)
* Autocomplete
  When for example you wish to create or rename a file and autocomplete is suggesting a similar filename, press C-M-j to enter avoiding the suggestion
* How to have user directory settings without altering the environment variables
  First make a .emacs file in the system HOME directory with the following code:
#  #+BEGIN_SRC emacs-lisp
#    ;; Place this file in C:/Users/chanyoungs and point to the appropriate files
#    (setq user-init-file "C:/Users/chanyoungs/Documents/Programming/emacs/.emacs.d/init.el")
#    (setq user-emacs-directory "C:/Users/chanyoungs/Documents/Programming/emacs/.emacs.d/")
#    (setq default-directory "C:/Users/chanyoungs/Documents/Programming/")
#    (setenv "HOME" "C:/Users/chanyoungs/Documents/Programming/emacs/")
#    (load user-init-file)
#  #+END_SRC

* New-line-without-break-of-line
  #+BEGIN_SRC emacs-lisp
    ;; newline-without-break-of-line
    (defun newline-without-break-of-line ()
      "1. move to end of the line.
      2. insert newline with index"

      (interactive)
      (let ((oldpos (point)))
	(end-of-line)
	(newline-and-indent)))

    (global-set-key (kbd "<C-return>") 'newline-without-break-of-line)
  #+END_SRC

* show-parens mode
  #+BEGIN_SRC emacs-lisp
    (setq show-paren-delay 0)
    (show-paren-mode 1)
  #+END_SRC
* Interface tweaks
  #+BEGIN_SRC emacs-lisp
    (setq inhibit-startup-message t)
    (fset 'yes-or-no-p 'y-or-n-p)
    (global-set-key (kbd "<f5>") 'revert-buffer)
    (global-set-key (kbd "C-x C-b") 'ibuffer)
  #+END_SRC
** Linenumbers
   #+BEGIN_SRC emacs-lisp
     (global-linum-mode t)
   #+END_SRC

** Delete selection mode
   When typing with text highlighted, it replaces it
   #+BEGIN_SRC emacs-lisp
     (delete-selection-mode 1)
   #+END_SRC

* Try
  #+BEGIN_SRC emacs-lisp
    (use-package try
      :ensure t)

  #+END_SRC

* Which key
  Brings up some help
  #+BEGIN_SRC emacs-lisp
    (use-package which-key
      :ensure t
      :config (which-key-mode))
  #+END_SRC
  
* Org-mode
# ** Org bullets
#    For some reason, org-bullets causes org-mode and swiper to be extremely slow.
#    #+BEGIN_SRC emacs-lisp
#      (use-package org-bullets
#        :ensure t
#        :config
#        (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1))))
#    #+END_SRC

** Hide leading stars
   #+BEGIN_SRC emacs-lisp
    (setq org-hide-leading-stars t)
   #+END_SRC

** Load languages on demand
   #+BEGIN_SRC emacs-lisp
    (defadvice org-babel-execute-src-block (around load-language nil activate)
      "Load language if needed"
      (let ((language (org-element-property :language (org-element-at-point))))
	(unless (cdr (assoc (intern language) org-babel-load-languages))
	  (add-to-list 'org-babel-load-languages (cons (intern language) t))
	  (org-babel-do-load-languages 'org-babel-load-languages org-babel-load-languages))
	ad-do-it))
   #+END_SRC
** Disable execution prompts
   #+BEGIN_SRC emacs-lisp
     (defun my-org-confirm-babel-evaluate (lang body)
       (not (string= lang "python")))  ; don't ask for python
     (setq org-confirm-babel-evaluate 'my-org-confirm-babel-evaluate)
   #+END_SRC
  
** Example code block evaluation
   Use C-c C-c to evaluate
   #+BEGIN_SRC python :results output
     print('Hello world!')
   #+END_SRC

   #+RESULTS:
   : Hello world!

* Ace-window
  #+BEGIN_SRC emacs-lisp
    (use-package ace-window
      :ensure t
      :init
    (progn
      (global-set-key [remap other-window] 'ace-window)
      (custom-set-faces
       '(aw-leading-char-face
         ((t (:inherit ace-jump-face-foreground :height 3.0)))))
      ))
  #+END_SRC

* Counsel(with yank-pop) and Swiper(counsel is dependent package)
  C-s to search then use C-p and C-n to move to search items in other lines. C-s [string] C-'(swiper-avy) can also let search in same lines.
  #+BEGIN_SRC emacs-lisp
    (use-package counsel
      :ensure t
      :bind
      (("M-y" . counsel-yank-pop)
      :map ivy-minibuffer-map
      ("M-y" . ivy-next-line)
      ))

    (use-package swiper
      :ensure t
      :config
      (progn
	(ivy-mode 1)
	(setq ivy-use-virtual-buffers t)
	(setq enable-recursive-minibuffers t)
	(global-set-key "\C-s" 'swiper)
	(global-set-key (kbd "C-c C-r") 'ivy-resume)
	(global-set-key (kbd "<f6>") 'ivy-resume)
	(global-set-key (kbd "M-x") 'counsel-M-x)
	(global-set-key (kbd "C-x C-f") 'counsel-find-file)
	(global-set-key (kbd "<f1> f") 'counsel-describe-function)
	(global-set-key (kbd "<f1> v") 'counsel-describe-variable)
	(global-set-key (kbd "<f1> l") 'counsel-find-library)
	(global-set-key (kbd "<f2> i") 'counsel-info-lookup-symbol)
	(global-set-key (kbd "<f2> u") 'counsel-unicode-char)
	(global-set-key (kbd "C-c g") 'counsel-git)
	(global-set-key (kbd "C-c j") 'counsel-git-grep)
	(global-set-key (kbd "C-c k") 'counsel-ag)
	(global-set-key (kbd "C-x l") 'counsel-locate)
	(global-set-key (kbd "C-S-o") 'counsel-rhythmbox)
	(define-key read-expression-map (kbd "C-r") 'counsel-expression-history)
	))

  #+END_SRC
* Expand-region
  C-= to expand region
  #+BEGIN_SRC emacs-lisp
    (use-package expand-region
      :ensure t
      :config
      (global-set-key (kbd "C-=") 'er/expand-region))
    (setq shift-select-mode nil) ;; When you expand region then C-g for some reason has conflict with transient-mark-mode
  #+END_SRC
  
* iedit, narrowing-widening
  C-; to iedit. Basically search and replace simultaneously
  To be used with expand-region, narrowing-widening
  #+BEGIN_SRC emacs-lisp
    (use-package iedit
      :ensure t)
  #+END_SRC
  C-x n to narrow/widen
  #+BEGIN_SRC emacs-lisp
    (define-prefix-command 'endless/toggle-map)
    ;; The manual recommends C-c for user keys, but C-x t is
    ;; always free, whereas C-c t is used by some modes.
    (define-key ctl-x-map "t" 'endless/toggle-map)
    (define-key endless/toggle-map "c" #'column-number-mode)
    (define-key endless/toggle-map "d" #'toggle-debug-on-error)
    (define-key endless/toggle-map "e" #'toggle-debug-on-error)
    (define-key endless/toggle-map "f" #'auto-fill-mode)
    (define-key endless/toggle-map "l" #'toggle-truncate-lines)
    (define-key endless/toggle-map "q" #'toggle-debug-on-quit)
    (define-key endless/toggle-map "t" #'endless/toggle-theme)
    ;;; Generalized version of `read-only-mode'.
    (define-key endless/toggle-map "r" #'dired-toggle-read-only)
    (autoload 'dired-toggle-read-only "dired" nil t)
    (define-key endless/toggle-map "w" #'whitespace-mode)

    (defun narrow-or-widen-dwim (p)
      "Widen if buffer is narrowed, narrow-dwim otherwise.
    Dwim means: region, org-src-block, org-subtree, or
    defun, whichever applies first. Narrowing to
    org-src-block actually calls `org-edit-src-code'.

    With prefix P, don't widen, just narrow even if buffer
    is already narrowed."
      (interactive "P")
      (declare (interactive-only))
      (cond ((and (buffer-narrowed-p) (not p)) (widen))
            ((region-active-p)
             (narrow-to-region (region-beginning)
                               (region-end)))
            ((derived-mode-p 'org-mode)
             ;; `org-edit-src-code' is not a real narrowing
             ;; command. Remove this first conditional if
             ;; you don't want it.
             (cond ((ignore-errors (org-edit-src-code) t)
                    (delete-other-windows))
    	       ((ignore-errors (org-narrow-to-block) t))
    	       (t (org-narrow-to-subtree))))
            ((derived-mode-p 'latex-mode)
             (LaTeX-narrow-to-environment))
            (t (narrow-to-defun))))

    (define-key endless/toggle-map "n"
      #'narrow-or-widen-dwim)
    ;; This line actually replaces Emacs' entire narrowing
    ;; keymap, that's how much I like this command. Only
    ;; copy it if that's what you want.
    (define-key ctl-x-map "n" #'narrow-or-widen-dwim)
    (add-hook 'LaTeX-mode-hook
              (lambda ()
                (define-key LaTeX-mode-map "\C-xn"
    	      nil)))
  #+END_SRC
* Auto-complete
    #+BEGIN_SRC emacs-lisp
      (use-package auto-complete
        :ensure t
        :init
        (progn
          (ac-config-default)
          (global-auto-complete-mode t)
          (add-to-list 'ac-dictionary-directories "~/.emacs.d/dict")
          ))
    #+END_SRC

* Themes
    #+BEGIN_SRC emacs-lisp
      ;; (use-package color-theme
      ;;   :ensure t)

      ;; (use-package zenburn-theme
      ;;   :ensure t
      ;;   :config (load-theme 'zenburn t))

      ;; (use-package monokai-theme
      ;;   :ensure t
      ;;   :config (load-theme 'monokai t))

      ;; (use-package ample-theme
      ;;   :init (progn (load-theme 'ample t t)
      ;;     	     (load-theme 'ample-flat t t)
      ;;     	     (load-theme 'ample-light t t)
      ;;     	     (enable-theme 'ample))
      ;;   :defer t
      ;;   :ensure t

      ;; (use-package atom-one-dark-theme
      ;;   :ensure t
      ;;   :config (load-theme 'atom-one-dark t))

      ;; (use-package tangotango-theme
      ;;   :ensure t
      ;;   :config (load-theme 'tangotango t))
      (load-theme 'atom-one-dark t)
    #+END_SRC

* Reveal.js
   #+BEGIN_SRC emacs-lisp
     (setq org-reveal-mathjax t)
     (use-package ox-reveal
       :ensure ox-reveal)
     (setq org-reveal-root "http://cdn.jsdelivr.net/reveal.js/3.0.0/"
   	)

   #+END_SRC
* smartparens
    #+BEGIN_SRC emacs-lisp
      (use-package smartparens
        :ensure t
        :config (require 'smartparens-config)
        :init (smartparens-global-mode t))
    #+END_SRC
  
* python
** path
   #+BEGIN_SRC emacs-lisp
     (setenv "PATH"
	     (concat
	      "C:/Users/chanyoungs/Anaconda2/Scripts/" ";"
	      (getenv "PATH")
	      )
	     )   
   #+END_SRC
** outside of emacs:
   Make sure that you have:
    1. pip
    2. pip install virtualenv
    [[https://www.youtube.com/watch?v=6BlTGPsjGJk][Emacs as a Python IDE - youtube]]
** Bug fix
   Warning...
   https://www.bountysource.com/issues/26370019-emacs-hangs-if-python-block-is-not-executed
   #+BEGIN_SRC emacs-lisp
     (setq python-shell-completion-native-enable nil)
     ;; (setq python-shell-prompt-detect-failure-warning nil)

     ;; (with-eval-after-load 'python
     ;;   (defun python-shell-completion-native-try ()
     ;;     "Return non-nil if can trigger native completion."
     ;;     (let ((python-shell-completion-native-enable t)
     ;;        (python-shell-completion-native-output-timeout
     ;;    	python-shell-completion-native-try-output-timeout))
     ;;    (python-shell-completion-native-get-completions
     ;;     (get-buffer-process (current-buffer))
     ;;     nil "_"))))
   #+END_SRC
** Flycheck 
*** outside of meacs:
    For Flycheck to work properly, you need the correct dlls. Easiest way is to use [[https://github.com/zklhp/emacs-w64/releases][emacs-w64]]
    If you get "libxml2 library not found" error, copy and paste the libxml2.dll file in the bin folder of your emacs(files are in emacs.d)
    for some reason, the actual files seem to be these 2 files: "zlib1.dll" & "libiconv-2.dll"
    https://emacs.stackexchange.com/questions/3874/easiest-way-to-install-emacs-windows-support-libraries
    https://sourceforge.net/projects/emacsbinw64/

*** emacs-lisp:
    #+BEGIN_SRC emacs-lisp
      (use-package flycheck
        :ensure t
        :init
        (global-flycheck-mode t))
    #+END_SRC
** Jedi
    #+BEGIN_SRC emacs-lisp
      (use-package jedi
	:ensure t
	:init
	(add-hook 'python-mode-hook 'jedi:setup)
	(add-hook 'python-mode-hook 'jedi:ac-setup))
	;; (remove-hook 'python-mode-hook 'ac-modes)
    #+END_SRC

** exec-path-from-shell
    #+BEGIN_SRC emacs-lisp
      (use-package exec-path-from-shell
        :ensure t)
    #+END_SRC

** Projectile
     #+BEGIN_SRC emacs-lisp
       (use-package projectile
         :ensure    projectile
         :config    (projectile-global-mode t)
         :diminish   projectile-mode)
     #+END_SRC

** epc
     #+BEGIN_SRC emacs-lisp
       (use-package epc
         :ensure t)
     #+END_SRC
** elpy
     #+BEGIN_SRC emacs-lisp
       (use-package elpy
         :ensure t
         :config
         (elpy-enable))
     #+END_SRC

** ein
   Emacs ipython editor
   #+BEGIN_SRC emacs-lisp
     (use-package ein
       :ensure t)
   #+END_SRC
   
   Save error hack
   #+BEGIN_SRC emacs-lisp
     ;; ;;; my hack to calls ein:notebook-save-notebook-command when in ein mode
     ;; (defun save-buffer (&optional arg)
     ;;   (interactive "p")
     ;;   (if (eq major-mode 'ein:notebook-multilang-mode)
     ;;       (ein:notebook-save-notebook-command)
     ;;     (let ((modp (buffer-modified-p))
     ;; 	  (make-backup-files (or (and make-backup-files (not (eq arg 0)))
     ;; 				 (memq arg '(16 64)))))
     ;;       (and modp (memq arg '(16 64)) (setq buffer-backed-up nil))
     ;;       (if (and modp (buffer-file-name))
     ;; 	  (message "Saving file %s..." (buffer-file-name)))
     ;;       (basic-save-buffer)
     ;;       (and modp (memq arg '(4 64)) (setq buffer-backed-up nil)))))

     ;; ;;; advice /defadvice that fails
     ;; (defun save-ein()
     ;;   (if (eq major-mode 'ein:notebook-multilang-mode)
     ;;       (ein:notebook-save-notebook-command))))
     ;; (advice-add 'save-buffer :before #'save-ein)
   #+END_SRC
     
** conda
     #+BEGIN_SRC emacs-lisp
       (use-package conda
	 :ensure t)
       (custom-set-variables
	'(conda-anaconda-home "C:/Users/chanyoungs/Anaconda2"))
     #+END_SRC
* yasnippet
   #+BEGIN_SRC emacs-lisp
     (use-package yasnippet
       :ensure t
       :init
       (yas-global-mode 1)
       )

   #+END_SRC

* auto-yasnippet
   #+BEGIN_SRC emacs-lisp
     (use-package auto-yasnippet
       :ensure t)
     (global-set-key (kbd "C-c y c") #'aya-create)
     (global-set-key (kbd "C-c y e") #'aya-expand)
     (global-set-key (kbd "C-o") #'aya-open-line)
   #+END_SRC

* Javascript
** outside of emacs
   If you get "libxml2 library not found" error, copy and paste the libxml2.dll file in the bin folder of your emacs(files are in emacs.d)
   for some reason, the actual files seem to be these 2 files: "zlib1.dll" & "libiconv-2.dll"
   https://emacs.stackexchange.com/questions/3874/easiest-way-to-install-emacs-windows-support-libraries
   https://sourceforge.net/projects/emacsbinw64/
** hide codeblocks
     #+BEGIN_SRC emacs-lisp
       (add-hook 'js-mode-hook
                 (lambda ()
                   ;; Scan the file for nested code blocks
                   (imenu-add-menubar-index)
                   ;; Activate the folding mode
                   (hs-minor-mode t)))
     #+END_SRC
** js2-mode
     #+BEGIN_SRC emacs-lisp
       (use-package js2-mode
         :mode "\\.js\\'"
         :commands js2-mode
         :config
         (setq-default
          js2-auto-indent-flag nil
          js2-basic-offset 4
          js2-electric-keys nil
          js2-enter-indents-newline nil
          js2-mirror-mode nil
          js2-mode-show-parse-errors nil
          js2-mode-show-strict-warnings nil
          js2-mode-squeeze-spaces t
          js2-strict-missing-semi-warning nil
          js2-strict-trailing-comma-warning nil
          js2-bounce-indent-p t
          js2-global-externs (list "$" "ko" "_")
          js2-highlight-external-variables t
          js2-mode-show-parse-errors t
          js2-mode-show-strict-warnings t)
         (add-hook 'js2-mode-hook 'flycheck-mode))
     #+END_SRC
** simple-httpd
     #+BEGIN_SRC emacs-lisp
       (use-package simple-httpd
         :ensure t)
     #+END_SRC
** skewer mode
     #+BEGIN_SRC emacs-lisp
       ;; (use-package skewer-mode
       ;;   :ensure t)
       ;; (add-hook 'js2-mode-hook 'skewer-mode)
       ;; (add-hook 'css-mode-hook 'skewer-css-mode)
       ;; (add-hook 'html-mode-hook 'skewer-html-mode)
     #+END_SRC
** impatient mode
     #+BEGIN_SRC emacs-lisp
       (use-package impatient-mode
         :ensure t)
      #+END_SRC
** typescript mode
     #+BEGIN_SRC emacs-lisp
       (use-package typescript-mode
	 :ensure t)
      #+END_SRC

** webmode
     #+BEGIN_SRC emacs-lisp
       (use-package web-mode
	 :ensure t)


       (add-to-list 'auto-mode-alist '("/project/dir/.*\\.js\\'" . web-mode))
       (setq web-mode-content-types-alist
	     '(("jsx"  . "/project/dir/.*\\.js[x]?\\'")))
       (add-to-list 'auto-mode-alist '("\\.jsx$" . web-mode))

       (add-to-list 'auto-mode-alist '("\\.tsx\\'" . web-mode))
       (add-hook 'web-mode-hook
		 (lambda ()
		   (when (string-equal "tsx" (file-name-extension buffer-file-name))
		     (setup-tide-mode))))

       ;; disable jshint since we prefer eslint checking
       (setq-default flycheck-disabled-checkers
		     (append flycheck-disabled-checkers
			     '(javascript-jshint)))

       ;; use eslint with web-mode for jsx files
       (flycheck-add-mode 'javascript-eslint 'web-mode)
       (flycheck-add-mode 'javascript-eslint 'javascript-mode)
      #+END_SRC
   
** reactmode
     #+BEGIN_SRC emacs-lisp
       (use-package rjsx-mode
	 :ensure t)
       (add-to-list 'auto-mode-alist '("components\\/.*\\.js\\'" . rjsx-mode))
       (add-to-list 'auto-mode-alist '("\\.tsx\\'" . rjsx-mode))
       (flycheck-add-mode 'javascript-eslint 'rjsx-mode)
     #+END_SRC
   
* nameses
  <f9> ¡ú Load an existing session
  Ctrl-u <f9> ¡ú Create new session (you¡¯ll be asked for a name)
  Ctrl-Shift-<f9> ¡ú Save session (you¡¯ll be asked for a name)
  Ctrl-<f9> ¡ú Switch to previous session
  #+BEGIN_SRC emacs-lisp
    (load "nameses")
    (require 'desktop)
    (require 'nameses)
    (global-set-key (kbd "<f9>")     'nameses-load)
    (global-set-key (kbd "C-<f9>")   'nameses-prev)
    (global-set-key (kbd "C-S-<f9>") 'nameses-save)
  #+END_SRC
* magit
** outside of emacs:
*** You should install git and add git to the PATH environment variable which is roughly at C:\Users\chanyoungs\AppData\Local\GitHub\PortableGit_f02737a78695063deace08e96d5042710d3e32db\cmd\
*** You should make sure that sh.exe is also added to the PATH environment variable at C:\Users\chanyoungs\AppData\Local\GitHub\PortableGit_f02737a78695063deace08e96d5042710d3e32db\usr\bin\
*** You should have repositories at ssh as opposed to https https://help.github.com/articles/changing-a-remote-s-url/
*** Best to install and use Putty to avoid password insertion which seems to cause problems on Windows http://guides.beanstalkapp.com/version-control/git-on-windows.html
** Magit instructions
   Getting started with Magit is really easy:
  
   M-x magit-status to see git status, and in the status buffer:
   s to stage files
   c c to commit (type the message then C-c C-c to actually commit)
   b b to switch to another branch
   Other handy keys:
  
   P u to do a git push
   F u to do a git pull
   try to press TAB
** Emacs-lisp
  #+BEGIN_SRC emacs-lisp
    (use-package magit
      :ensure t)
    (global-set-key (kbd "C-x g") 'magit-status)
    (setenv "GIT_SSH" "C:/Program Files/PuTTY/plink.exe")
  #+END_SRC
* undo-tree
  C-/ to undo, C-S-/ to redo
  C-x u to run undo tree, d in undo-tree to see diffs
  
  #+BEGIN_SRC emacs-lisp
    (use-package undo-tree
         :ensure t
         :init
         (global-undo-tree-mode))
  #+END_SRC
* Highlight line & Beacon mode
  #+BEGIN_SRC emacs-lisp
    (global-hl-line-mode t)
  #+END_SRC

  #+BEGIN_SRC emacs-lisp
    (use-package beacon
      :ensure t
      :config
      (beacon-mode 1)
      (setq beacon-color "#666600")
      )
  #+END_SRC
* Highlight-indentation-mode
  #+BEGIN_SRC emacs-lisp
  (set-face-background 'highlight-indentation-face "gray20")
  (set-face-background 'highlight-indentation-current-column-face "dark red")
  #+END_SRC
* Browse-url-dwim
  C-c b (mnemonic: b for browse)
  or select some text and press C-c g (mnemonic: g for Google)
  #+BEGIN_SRC emacs-lisp
    (use-package browse-url-dwim
      :ensure t)
    (require 'browse-url-dwim)

    (browse-url-dwim-mode 1)

    ;; place the cursor on a URL
    ;; press "C-c b"

    ;; select some text
    ;; press "C-c g"

    ;; to turn off confirmations
    (setq browse-url-dwim-always-confirm-extraction nil)

    ;; set specific browser to open links
    (setq browse-url-browser-function 'browse-url-default-windows-browser)
  #+END_SRC

* ac-math
  #+BEGIN_SRC emacs-lisp
    (use-package ac-math
      :ensure t
      )
  #+END_SRC
* dtrt-indent
  #+BEGIN_SRC emacs-lisp
    (use-package dtrt-indent
      :ensure t)
  #+END_SRC
* prettier
  #+BEGIN_SRC emacs-lisp
    (use-package prettier-js
      :ensure t)
    (add-hook 'js2-mode-hook 'prettier-js-mode)
    (add-hook 'web-mode-hook 'prettier-js-mode)
    (add-hook 'rjsx-mode-hook 'prettier-js-mode)
  #+END_SRC
* typescript(tide)
  #+BEGIN_SRC emacs-lisp
		(use-package tide
			:ensure t
			:after (typescript-mode company flycheck)
			:hook ((typescript-mode . tide-setup)
						 (typescript-mode . tide-hl-identifier-mode)
						 (before-save . tide-format-before-save)))

		(add-hook 'rjsx-mode-hook 'tide-mode)
  #+END_SRC
* Atomic Chrome
  #+BEGIN_SRC emacs-lisp
    (use-package atomic-chrome
      :ensure t
      :config
      (atomic-chrome-start-server))
  #+END_SRC
